### ISSUE TITLE
LDP syntactic annotation

### ISSUE THREAD

**Issue by mfedzech** [rcc-uchicago/ldp#11]
Erica Cartmill tells me that that the following 18 P2 families contain syntactic annotation for all sessions for adults and children:
24
29
33
37
42
43
44
48
50
62
74
77
78
84
88
92
103
105

The only syntactic annotation I find in my version, however, is only for session 9 (all families). Is it possible that I'm using an older version of the database or are these parsed families stored somewhere else? I'd really need to get hold of them somehow.

Thanks!

**Comment by joyrexus** [comment]
@mfedzech Closing for now. If my previous comment doesn't resolve your issue, let me know and I'll re-open this issue.
